// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceXdpCpumapEnqueue  *ebpf.ProgramSpec `ebpf:"trace_xdp_cpumap_enqueue"`
	TraceXdpCpumapKthread  *ebpf.ProgramSpec `ebpf:"trace_xdp_cpumap_kthread"`
	TraceXdpDevmapXmit     *ebpf.ProgramSpec `ebpf:"trace_xdp_devmap_xmit"`
	TraceXdpException      *ebpf.ProgramSpec `ebpf:"trace_xdp_exception"`
	TraceXdpRedirect       *ebpf.ProgramSpec `ebpf:"trace_xdp_redirect"`
	TraceXdpRedirectErr    *ebpf.ProgramSpec `ebpf:"trace_xdp_redirect_err"`
	TraceXdpRedirectMap    *ebpf.ProgramSpec `ebpf:"trace_xdp_redirect_map"`
	TraceXdpRedirectMapErr *ebpf.ProgramSpec `ebpf:"trace_xdp_redirect_map_err"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	CpumapEnqueueCnt *ebpf.MapSpec `ebpf:"cpumap_enqueue_cnt"`
	CpumapKthreadCnt *ebpf.MapSpec `ebpf:"cpumap_kthread_cnt"`
	DevmapXmitCnt    *ebpf.MapSpec `ebpf:"devmap_xmit_cnt"`
	ExceptionCnt     *ebpf.MapSpec `ebpf:"exception_cnt"`
	RedirectErrCnt   *ebpf.MapSpec `ebpf:"redirect_err_cnt"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	CpumapEnqueueCnt *ebpf.Map `ebpf:"cpumap_enqueue_cnt"`
	CpumapKthreadCnt *ebpf.Map `ebpf:"cpumap_kthread_cnt"`
	DevmapXmitCnt    *ebpf.Map `ebpf:"devmap_xmit_cnt"`
	ExceptionCnt     *ebpf.Map `ebpf:"exception_cnt"`
	RedirectErrCnt   *ebpf.Map `ebpf:"redirect_err_cnt"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.CpumapEnqueueCnt,
		m.CpumapKthreadCnt,
		m.DevmapXmitCnt,
		m.ExceptionCnt,
		m.RedirectErrCnt,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceXdpCpumapEnqueue  *ebpf.Program `ebpf:"trace_xdp_cpumap_enqueue"`
	TraceXdpCpumapKthread  *ebpf.Program `ebpf:"trace_xdp_cpumap_kthread"`
	TraceXdpDevmapXmit     *ebpf.Program `ebpf:"trace_xdp_devmap_xmit"`
	TraceXdpException      *ebpf.Program `ebpf:"trace_xdp_exception"`
	TraceXdpRedirect       *ebpf.Program `ebpf:"trace_xdp_redirect"`
	TraceXdpRedirectErr    *ebpf.Program `ebpf:"trace_xdp_redirect_err"`
	TraceXdpRedirectMap    *ebpf.Program `ebpf:"trace_xdp_redirect_map"`
	TraceXdpRedirectMapErr *ebpf.Program `ebpf:"trace_xdp_redirect_map_err"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceXdpCpumapEnqueue,
		p.TraceXdpCpumapKthread,
		p.TraceXdpDevmapXmit,
		p.TraceXdpException,
		p.TraceXdpRedirect,
		p.TraceXdpRedirectErr,
		p.TraceXdpRedirectMap,
		p.TraceXdpRedirectMapErr,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed bpf_bpfel.o
var _BpfBytes []byte
