// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	XdpIcmpEchoFunc    *ebpf.ProgramSpec `ebpf:"xdp_icmp_echo_func"`
	XdpPassFunc        *ebpf.ProgramSpec `ebpf:"xdp_pass_func"`
	XdpRedirectFunc    *ebpf.ProgramSpec `ebpf:"xdp_redirect_func"`
	XdpRedirectMapFunc *ebpf.ProgramSpec `ebpf:"xdp_redirect_map_func"`
	XdpRouterFunc      *ebpf.ProgramSpec `ebpf:"xdp_router_func"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	RedirectParams *ebpf.MapSpec `ebpf:"redirect_params"`
	TxPort         *ebpf.MapSpec `ebpf:"tx_port"`
	XdpStatsMap    *ebpf.MapSpec `ebpf:"xdp_stats_map"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	RedirectParams *ebpf.Map `ebpf:"redirect_params"`
	TxPort         *ebpf.Map `ebpf:"tx_port"`
	XdpStatsMap    *ebpf.Map `ebpf:"xdp_stats_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.RedirectParams,
		m.TxPort,
		m.XdpStatsMap,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	XdpIcmpEchoFunc    *ebpf.Program `ebpf:"xdp_icmp_echo_func"`
	XdpPassFunc        *ebpf.Program `ebpf:"xdp_pass_func"`
	XdpRedirectFunc    *ebpf.Program `ebpf:"xdp_redirect_func"`
	XdpRedirectMapFunc *ebpf.Program `ebpf:"xdp_redirect_map_func"`
	XdpRouterFunc      *ebpf.Program `ebpf:"xdp_router_func"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.XdpIcmpEchoFunc,
		p.XdpPassFunc,
		p.XdpRedirectFunc,
		p.XdpRedirectMapFunc,
		p.XdpRouterFunc,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed bpf_bpfel.o
var _BpfBytes []byte
